### ISSUE TITLE
[Bug] The plugin does not work on 1.8.8

### ISSUE THREAD

**Issue by djhbznz** [Bram1903/MinecraftPlayerCrasher#13]
plugin version: 2.5.0

[14:15:22 ERROR]: Could not load 'plugins\PlayerCrasher-2.5.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/github/retrooper/packetevents/event/PacketListenerCommon
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
Caused by: java.lang.NoClassDefFoundError: com/github/retrooper/packetevents/event/PacketListenerCommon
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_362]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_362]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.github.retrooper.packetevents.event.PacketListenerCommon
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_362]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_362]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_362]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_362]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_362]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        ... 6 more

**Comment by djhbznz** [comment]
also plugin version 2.4.0

**Comment by djhbznz** [comment]
plugin version: 2.3.1
<Plugin isn't showing any return value when typing /crash>
both console and in game

**Comment by djhbznz** [comment]
it does work in 2.2.0
![ZYU_)FANPWV8CJ19722(5H0](https://github.com/Bram1903/MinecraftPlayerCrasher/assets/144500879/92357e9b-0e8a-4fff-82e4-e2e0df308ba0)

**Comment by Bram1903** [comment]
Hey, 

I am currently in the middle of rewriting this entire plugin, so I will make sure that this will be fixed in the new versions as well!

Kind regards,
Bram

**Comment by djhbznz** [comment]
thank you！

**Comment by Bram1903** [comment]
Hey @djhbznz, 

I made a small mistake and marked PacketEvents as a soft dependency instead of a required dependency. The reason you are seeing that error is because you do not have PacketEvents installed! Could you install [PacketEvents](https://modrinth.com/plugin/packetevents/versions) and give it another shot?

If you want you can install my latest snapshot build which hasn't yet been released, but is a completely rewritten version that has been greatly improved. You will still need PacketEvents however :-)
https://github.com/Bram1903/MinecraftPlayerCrasher/actions/runs/9596995167/artifacts/1620529388

Thanks in advance!

Kind regards,
Bram

**Comment by djhbznz** [comment]
Hmmm

[22:13:29 ERROR]: Could not load 'plugins\PlayerCrasher-3.0.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: packetevents
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:218) [BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [BurritoSpigot.jar:git-BurritoSpigot-"bec78e2"]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]

**Comment by Bram1903** [comment]
@djhbznz, make sure that you install PacketEvents as a dependency! You can find [the download here](https://modrinth.com/plugin/packetevents/versions)! Make sure to grab the spigot version.

**Comment by Bram1903** [comment]
@djhbznz, this is an issue with newer versions of ViaVersion because they added support for 1.21! You can download a snapshot release from PacketEvents that solved this issue here:

https://ci.codemc.io/job/retrooper/job/packetevents/lastSuccessfulBuild/artifact/spigot/build/libs/packetevents-spigot-2.3.1-SNAPSHOT.jar

**Comment by djhbznz** [comment]
it does work, thank you!

**Comment by Bram1903** [comment]
Great to hear!
